# Site settings
  # Note: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.
  # When filling this file in, below, be sure to DELETE the "#" comments - example, greeting should look like - greeting: Hello, I'm Simpol.

#content for nav.html
title: XRV | A blog
subtitle: Focus on the writing, the content.

#content for index.html
  #Add your own info, deleting the comments "#". This data automatically writes to the Index page's mini, about section.
greeting: Hello, I'am Xander
logo_img: /assets/img/header.png
subgreeting_one: #SUBGREETING_ONE_GOES_HERE
subgreeting_two: #SUBGREETING_TWO_GOES_HERE

# Again: after inputting your content, you may need to stop and restart jekyll server for changes to take effect.

#content for nav.html (shown on desktop) navigation links
nav_link_one_name: Overview
nav_link_one_link: "/"

nav_link_two_name: Categories
nav_link_two_link: "/categories"

nav_link_three_name: #NAV_NAME_GOES_HERE
nav_link_three_link: #NAV_LINK_GOES_HERE

#content for footer.html (shown on mobile) footer navigation links
footer_link_one_name: #FOOTER_NAME_GOES_HERE
footer_link_one_link: #FOOTER_LINK_GOES_HERE

footer_link_two_name: Categories
footer_link_two_link: "/categories"

footer_link_three_name: #FOOTER_NAME_GOES_HERE
footer_link_three_link: #FOOTER_LINK_GOES_HERE

baseurl: ""
google_tracking_id: UA-26371954-1
copyright_name: Mathson Design, LLC

# SEO data (https://github.com/jekyll/jekyll-seo-tag)
logo: /assets/img/simpol-favicon.png
description: XRV blogging about coding, infrastructure, scrum, at scale
author:
  name: Xander Verheij
  email: xander@xrv.nl
  twitter: xanderv87

social:
  name: Xander Verheij
  links:
    - https://twitter.com/xanderv87
    - https://github.com/xanderv87
    - https://www.linkedin.com/in/xrverheij/

# Build settings
permalink: pretty
paginate: 12


defaults:
  -
    scope:
      path: "assets/img"
    values:
      image: true

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
exclude:
- Gemfile
- Gemfile.lock
- package.json
- README.md
- vendor
- .idea
